<div class="p-5 mb-4 rounded-3">
    <h1 class="display-7 fw-bold">About Me</h1>
    <div class="container-fluid">
        <p class="fs-5">Hello guys, I'm Kaushal Bhatol from India and this page is all about my journey of coding life and what I'll do in my daily base life for improving myself. In the year 2021, I'm in Bsc IT & IMS at Ganpat University Ahemdabad as a first-year college student. my age is around 19yrs on this particular year.</p>
        <p class="fs-5">"Something is better than nothing" following this beautiful line, I just created this blog and  I have something to remember for my life journey. </p>
        <p class="fs-5">I want to become a network engineer as well as an ethical hacker too. learning new stuff every day and remember in this small mind is not a great idea for me, because every time I come back to the same condition and that was hard to remember what to do. So well documentation always helps me a lot and hope that it helps you also.</p>
        <p class="fs-5">I am addicted to creat MD files for documentation, which helps me a lot here too. my many things are just copy-pasted as MD files, and thanks to WordPress to recognized all files and converted them to beautiful web pages. Remember always good habit helps.</p>
        <p class="fs-5">"Great Thoughts Creat Great life" always try to positive in my life and as a programmer patent is the most luxurious thing to wear. every single time a bug hits like a bullet on my head, finding a solution is a great way to learn something new.</p>
        <p class="fs-5">I want to good network engineer for that I just used windows for around a year and shifted to Linux for a better grip on commands. I'm not able to play windows games on Linux, that's why I continuously work and grow in my life. also thankful to Linux for giving me great stability as well as performance and stopping to play windows games. this helps me to never distract from my goals, every time you start playing games you never know what important time you lost in that shit. keep discipline and never thought about games.</p>
        <p class="fs-5">Let's talk about my site. it was not awesome as others. I never thought to optimize this site because I always want to easy to maintainable and clean look to give you focus on what you & I want. Thanks to WordPress again to gives me what I want in one place. I know HTML, CSS as well as PHP also. But I don't want to waste my time on a blog site because you are just doing a stupid thing to create your own blog site. it was time-consuming and also not giving worth to you. if you want to create something always do the project for yourself, not a blog. I know also WordPress is slower than handmade sites, but easy to create and save lots of time.</p>
        <p class="fs-5">I know i'm not perfect in article writing but it was matter to me to create somthing which helps me to stand somthig bigger in my life, I learned that not everythings needs to be perfect. some things are looking awesome when that was imperfect.</p>
        <p>
            <a href="http://kaushal.my-style.in/me/" class="btn btn-secondary my-2">Contact Me</a>
        </p>
    </div>
</div>